### ISSUE TITLE
Créer un BackEnd pour fournir les activités à staffer

### ISSUE THREAD

**Issue by trollepierre** [octo-web-front-end-tribe/octo-job-board#11]
Remonter les données de l'API Octopod pour le front.  

Monter un serveur Express pour interroger l'API Octopod avec les informations/token de sécurité (à demander en privé à @trollepierre)

L'API à interroger est
https://octopod.octo.com/api/v0/projects/{id}/activities
cf https://octopod.octo.com/apidoc#/

L'URL pour fournir les résultats
"- l'URL des activités est "/api/jobs"

La story qui utilise le backend est #4 

Attendu : 
- il n'y a pas de trace des credentials Octopod dans le code
seules les activités ""à staffer"" sont remontées

**Comment by trollepierre** [comment]
Le résultat attendu par le front est : 
[
  {
    "id": 0,
    "title": "string",
    "nb_days": "string",
    "average_daily_rate": "string",
    "kind": 0,
    "staffing_needed": true,
    "project": {
      "id": 0,
      "url": "string",
      "name": "string",
      "kind": "string",
      "reference": "string",
      "status": "string",
      "customer": {
        "id": "string",
        "name": "string"
      }
    },
    "project_id": 0,
    "people": {
      "id": 0,
      "last_name": "string",
      "first_name": "string",
      "nickname": "string",
      "url": "string"
    }
  }
]

**Comment by trollepierre** [comment]
Swann et moi avons réalisé l'api pour nous renvoyer des fakes données (ci-dessus).
A toi, Anass, d'appeler Octopod et de récupérer les bonnes données

**Comment by trollepierre** [comment]
en corrigeant l'url /api/activities en /api/jobs, pensez à modifier le front

**Comment by jbuget** [comment]
le dernier point a été pris en compte dans le commit [4a13217](https://github.com/octo-web-front-end-tribe/octo-job-board/commit/4a13217eb5b980718fb942e989dc7f8ab8199a34)

**Comment by trollepierre** [comment]
![image](https://user-images.githubusercontent.com/8363334/27321244-b97edd80-5599-11e7-936c-182b3213be8b.png)
![image](https://user-images.githubusercontent.com/8363334/27321248-bbeb1250-5599-11e7-996d-c6e29d532653.png)

**Comment by trollepierre** [comment]
Projects avec staffing needed
https://octopod.octo.com/projects/2146905358?locale=fr
https://octopod.octo.com/projects/2146905351?locale=fr
