### ISSUE TITLE
Redirection http vers https

### ISSUE THREAD

**Issue by isselparra** [octo-web-front-end-tribe/octo-job-board#133]
Lorsque je me connecte sur l'url http://jobs.octo.com , je suis redirigé vers https://jobs.octo.com.

**Comment by trollepierre** [comment]
@isselparra : il sera intéressant de demander à @Akhilian (ou des autres) comment on peut faire ceci

**Comment by isselparra** [comment]
Vu avec @jbuget, il faut utiliser le module : 
https://www.npmjs.com/package/express-http-to-https
