### ISSUE TITLE
Modale d'intérêt : mettre à jour les boutons

### ISSUE THREAD

**Issue by ElsaTouzeau** [octo-web-front-end-tribe/octo-job-board#134]
- Supprimer les boutons 'Fiche Octopod' et 'Annuler'.
- Ajouter un bouton croix [X] pour quitter la modale. (l'insérer pour toutes les modales)
- Modifier le texte du bouton 'Envoyer' par 'Je suis disponible'.

**Comment by trollepierre** [comment]
@ElsaTouzeau @isselparra : ne pensez-vous pas qu'on pourrait intégrer ces changements dans la story #135 ?

**Comment by ElsaTouzeau** [comment]
Issue #134 intégrée à l'issue #135.
