### ISSUE TITLE
M'authentifier via mon compte (Google) OCTO

### ISSUE THREAD

**Issue by trollepierre** [octo-web-front-end-tribe/octo-job-board#2]
"- en tant que collaborateur non connecté, quand je tente d'accéder à une page autre que la page de connexion, alors je suis redirigé vers la page de connexion
- en tant que collaborateur connecté, je peux accéder à toutes les pages du site
- en tant que collaborateur connecté, quand j'accède à la page de connexion, je suis redirigé vers la page index
- l'URL de la page de connexion est ""/login""
- la page de connexion se résume à la mire de connexion Google Connect
- il n'y a pas de trace des credentials Google Connect dans le code (sécurité)"

**Comment by trollepierre** [comment]
Cheat Sheat : https://github.com/phanan/vue-google-signin-button

**Comment by trollepierre** [comment]
Ticket infra pour obtenir un client ID  de google connect : https://redmine.octo.com/issues/6365

**Comment by swannknani** [comment]
Est ce que le design de la page est compris dans l'US ?

**Comment by trollepierre** [comment]
Il me semble qu'il est à la convenance du développeur. 
Faisons simple : un bouton sur la page.
