### ISSUE TITLE
Me déconnecter

### ISSUE THREAD

**Issue by trollepierre** [octo-web-front-end-tribe/octo-job-board#3]
"- il est possible de se connecter via l'URL ""/logout""
- sur chaque page sécurisée, il existe un lien vers l'URL de déconnexion
- une fois que je suis déconnecté, je suis redirigé vers la page de connexion
- si je tente de me déconecter (via l'URL) alors que je ne suis pas connecté, alors je suis redirigé vers la page de connexion"
-ajouter la navbar http://jbuget.fr/job-board/

**Comment by swannknani** [comment]
@trollepierre  Pourquoi as tu bougé cette US dans Review tech et func ? Elle n'est pas encore terminée. J'expliquais cela dans l'US connection

**Comment by trollepierre** [comment]
mea culpam! ;-)

**Comment by jbuget** [comment]
done and deployed
