### ISSUE TITLE
Faire un composant JobsPage et revoir le composant JobList pour qu'il soit réutilisable (ex : pour les missions de type Consulting, Delivery ou Training)

### ISSUE THREAD

**Issue by jbuget** [octo-web-front-end-tribe/octo-job-board#38]
trier les missions par typologie : conseil | delivery | formation

**Comment by buinierdominique** [comment]
Je ne sais pas s'il faut les "trier". Peut-être plus les rendre "triables". En tout cas, donner l'information de manière explicite  sur chaque carte me parait importante

Je trouverais dommage qu'un consultant aille uniquement dans la partie triée " Delivery", sans aller voir les autres parties, car ponctuellement ça peut être bien qu'il fasse une mission de Conseil ou donne une formation.

**Comment by trollepierre** [comment]
Proposition ?
<img width="559" alt="capture d ecran 2017-07-14 a 11 39 06" src="https://user-images.githubusercontent.com/8363334/28281519-b0d288dc-6b27-11e7-8156-82583c2b4138.png">

**Comment by trollepierre** [comment]
blocked : jusqu'à retour de DOM

**Comment by trollepierre** [comment]
#38
L'idéal serait de mettre les tags "Delivery" "Conseil" "OCAC" proches du tag "Signé" ou "Propale" : soit juste à côté, soit en juste dessous. 

On aurait un truc du style : 
"Signé" "Delivery"

ou bien 
"Signé"
"Delivery"


Désolée, je n'ai pas de quoi faire rapidement un dessin ;)

Par ailleurs, je ne suis pas fan du code couleur "rouge". Et je ne suis pas persuadée qu'il faille avoir un code couleur par type de mission.
=> je pense qu'on peut rester sur le même code couleur que dans octopod :  fond gris.  WDYT ?

**Comment by trollepierre** [comment]
Viendra avec le nouveau design du Job board

**Comment by trollepierre** [comment]
closed by new design
