### ISSUE TITLE
Trier les activités entre les missions signées et les propales

### ISSUE THREAD

**Issue by trollepierre** [octo-web-front-end-tribe/octo-job-board#65]
L'objectif est de mettre les missions signées avant les propales en cours
Se rapprocher de JJA ou DOM pour qualifier quelles sont les différents statuts des activités sur Octopod

**Comment by buinierdominique** [comment]
A mon sens, on peut rester sur les 2 grandes catégories suivantes  : 
Propale : correspondrait dans octopod à 2 statuts :  "Propale en cours " ou "Propale envoyée"
Signé : correspondrait dans octopod à 2 statuts : "Accord client" ou "Contrat reçu"

**Comment by trollepierre** [comment]
#72
