### ISSUE TITLE
Ajouter le nombre d'Octos sur la mission

### ISSUE THREAD

**Issue by trollepierre** [octo-web-front-end-tribe/octo-job-board#67]

**Comment by buinierdominique** [comment]
à creuser 

je ne suis pas fan du "nombre de consultants déjà présents dans la mission" qui peut être = à 0 quand on démarre la recherche de staffing

cela pourrait être intéressant de donner "la taille de l'équipe OCTO" => l'info n'est pas dans octopod car aujourd'hui on a des lignes d'activités qui ne sont pas toujours  équivalentes 1 pour 1 au nombre de consultant

à creuser comment faire "facilement"...
