### ISSUE TITLE
BUG : Impossible de déclarer mon intérêt. Problème mailjet ?

### ISSUE THREAD

**Issue by trollepierre** [octo-web-front-end-tribe/octo-job-board#89]
Lorsque je clique sur "Je suis intéressé", rien ne se passe. Et je reçois une erreur.
Je suspecte Mailjet

**Comment by trollepierre** [comment]
<img width="1432" alt="capture d ecran 2017-08-11 a 17 21 10" src="https://user-images.githubusercontent.com/8363334/29219892-b3648104-7eb9-11e7-89f4-a7f96c6e74d6.png">

**Comment by jbuget** [comment]
Il s'agissait d'un problème de variables d'environnement sur les envs de staging et prod.
